module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    sourceType: "module"
  },
  plugins: [
    "@typescript-eslint/eslint-plugin",
    "rxjs",
  ],
  env: {
    node: true,
    browser: true,
    es6: true
  },
  rules: {
    "rxjs/finnish": "error",
    "array-bracket-spacing": ["error", "never"],
    "block-spacing": ["error", "always"],
    "brace-style": ["error", "1tbs"],
    "space-in-parens": ["error", "never"],
    "computed-property-spacing": ["error", "never"],
    "indent": [
      "error",
      2,
      {
        "MemberExpression": 0,
      },
    ],
    "arrow-body-style": ["error", "as-needed"],
    "comma-dangle": "off",
    "@typescript-eslint/comma-dangle": ["error", "always-multiline"],
    "no-constant-condition": "error",
    "no-duplicate-case": "error",
    "no-extra-boolean-cast": "error",
    "no-extra-semi": "error",
    "no-unexpected-multiline": "error",
    "arrow-spacing": [
      "error",
      {
        "before": true,
        "after": true,
      },
    ],
    "func-call-spacing": ["error", "never"],
    "newline-after-var": ["error", "always"],
    "padded-blocks": ["error", "never"],
    "no-multi-spaces": "error",
    "quote-props": ["error", "consistent-as-needed"],
    "no-duplicate-imports": "off",
    "@typescript-eslint/no-duplicate-imports": ["error"],
    "no-invalid-this": "off",
    "@typescript-eslint/no-invalid-this": ["error"],
    "no-cond-assign": "error",
    "arrow-parens": ["error", "always"],
    "no-sparse-arrays": "error",
    // "newline-before-return": "error"l // Unavailable in this version
    "no-redeclare": "error",
    "object-shorthand": "error",
    "no-multiple-empty-lines": ["error", { "max": 1}],
    "rxjs/no-unsafe-takeuntil": "error",
    "rxjs/no-internal": "error",
    "rxjs/no-create": "error",
    "rxjs/no-nested-subscribe": "error",
    "spaced-comment": ["error", "always"],
    "curly": ["error", "all"],
    "eol-last": ["error", "always"],
    "guard-for-in": "error",
    "no-labels": "error",
    "max-len": [
      "error",
      {
        "code": 120,
        "tabWidth": 2,
        "ignorePattern": "^(import|export)\s.+\sfrom\s.+;$"
      },
    ],
    "no-caller": "error",
    "no-bitwise": "error",
    "no-console": [
      "error",
      {
        allow: [
          "warn",
          "error",
          "log",
        ],
      },
    ],
    "no-new-wrappers": "error",
    "no-debugger": "error",
    "no-eval": "error",
    "no-shadow": "off",
    "@typescript-eslint/no-shadow": ["error"],
    "no-throw-literal": "error",
    "no-fallthrough": "error",
    "no-trailing-spaces": "error",
    "no-new": "error",
    "no-var": "error",
    "prefer-const": "error",
    "quotes": ["error", "single"],
    "semi": ["error", "always"],
    "eqeqeq": ["error", "always"],
    "@typescript-eslint/member-ordering": [
      "error",
      {
        "default": [
          "public-static-field",
          "public-instance-field",
          "protected-static-field",
          "protected-instance-field",
          "private-static-field",
          "private-instance-field",
          "public-constructor",
          "protected-constructor",
          "private-constructor",
          "public-static-method",
          "public-instance-method",
          "protected-instance-method",
          "private-instance-method",
        ],
      },
    ],
    "@typescript-eslint/no-empty-interface": [
      "error",
      {
        "allowSingleExtends": false,
      },
    ],
    "@typescript-eslint/no-floating-promises": "error",
  },
};
